export default [
    { is_reading: true,    title: "The Dead Zone",                                   year_published: 1979,  author: 'Stephen King',     },
    { is_reading: false,   title: "Firestarter",                                     year_published: 1980,  author: 'Stephen King',     },
    { is_reading: false,   title: "Roadwork",                                        year_published: 1980,  author: "Richard Bachman",  },
    { is_reading: false,   title: "Cujo",                                            year_published: 1981,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Running Man",                                 year_published: 1981,  author: "Richard Bachman",  },
    { is_reading: false,   title: "The Gunslinger (The Dark Tower I)",               year_published: 1982,  author: 'Stephen King',     },
    { is_reading: false,   title: "Christine",                                       year_published: 1983,  author: 'Stephen King',     },
    { is_reading: false,   title: "Pet Sematary",                                    year_published: 1983,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Talisman",                                    year_published: 1984,  author: 'Stephen King',     },
    { is_reading: false,   title: "Thinner",                                         year_published: 1984,  author: "Richard Bachman",  },
    { is_reading: false,   title: "Cycle of the Werewolf",                           year_published: 1985,  author: 'Stephen King',     },
    { is_reading: false,   title: "It",                                              year_published: 1986,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Eyes of the Dragon",                          year_published: 1987,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Drawing of the Three (The Dark Tower II)",    year_published: 1987,  author: 'Stephen King',     },
    { is_reading: false,   title: "Misery",                                          year_published: 1987,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Tommyknockers",                               year_published: 1987,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Dark Half",                                   year_published: 1989,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Waste Lands (The Dark Tower III)",            year_published: 1991,  author: 'Stephen King',     },
    { is_reading: false,   title: "Needful Things",                                  year_published: 1991,  author: 'Stephen King',     },
    { is_reading: false,   title: "Gerald's Game",                                   year_published: 1992,  author: 'Stephen King',     },
    { is_reading: false,   title: "Dolores Claiborne",                               year_published: 1993,  author: 'Stephen King',     },
    { is_reading: false,   title: "Insomnia",                                        year_published: 1994,  author: 'Stephen King',     },
    { is_reading: false,   title: "Rose Madder",                                     year_published: 1995,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Regulators",                                  year_published: 1995,  author: "Richard Bachman",  },
    { is_reading: false,   title: "The Green Mile",                                  year_published: 1996,  author: 'Stephen King',     },
    { is_reading: false,   title: "Desperation",                                     year_published: 1996,  author: 'Stephen King',     },
    { is_reading: false,   title: "Wizard and Glass (The Dark Tower IV)",            year_published: 1997,  author: 'Stephen King',     },
    { is_reading: false,   title: "Bag of Bones",                                    year_published: 1998,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Girl Who Loved Tom Gordon",                   year_published: 1999,  author: 'Stephen King',     },
    { is_reading: false,   title: "Dreamcatcher",                                    year_published: 2001,  author: 'Stephen King',     },
    { is_reading: false,   title: "Black House",                                     year_published: 2001,  author: 'Stephen King',     },
    { is_reading: false,   title: "From a Buick 8",                                  year_published: 2002,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Wolves of the Calla (The Dark Tower V)",      year_published: 2003,  author: 'Stephen King',     },
    { is_reading: false,   title: "Song of Susannah (The Dark Tower VI)",            year_published: 2004,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Dark Tower (The Dark Tower VII)",             year_published: 2004,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Colorado Kid",                                year_published: 2005,  author: 'Stephen King',     },
    { is_reading: false,   title: "Cell",                                            year_published: 2006,  author: 'Stephen King',     },
    { is_reading: false,   title: "Lisey's Story",                                   year_published: 2006,  author: 'Stephen King',     },
    { is_reading: false,   title: "Blaze",                                           year_published: 2006,  author: "Richard Bachman",  },
    { is_reading: false,   title: "Duma Key",                                        year_published: 2008,  author: 'Stephen King',     },
    { is_reading: false,   title: "Under the Dome",                                  year_published: 2009,  author: 'Stephen King',     },
    { is_reading: false,   title: "11/22/63",                                        year_published: 2011,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Wind Through the Keyhole (The Dark Tower)",   year_published: 2012,  author: 'Stephen King',     },
    { is_reading: false,   title: "Joyland",                                         year_published: 2013,  author: 'Stephen King',     },
    { is_reading: false,   title: "Doctor Sleep",                                    year_published: 2013,  author: 'Stephen King',     },
    { is_reading: false,   title: "Mr. Mercedes",                                    year_published: 2014,  author: 'Stephen King',     },
    { is_reading: false,   title: "Revival",                                         year_published: 2014,  author: 'Stephen King',     },
    { is_reading: false,   title: "Finders Keepers",                                 year_published: 2015,  author: 'Stephen King',     },
    { is_reading: false,   title: "End of Watch",                                    year_published: 2016,  author: 'Stephen King',     },
    { is_reading: false,   title: "Sleeping Beauties",                               year_published: 2017,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Outsider",                                    year_published: 2018,  author: 'Stephen King',     },
    { is_reading: false,   title: "The Institute",                                   year_published: 2019,  author: 'Stephen King',     },
    { is_reading: false,   title: "Later",                                           year_published: 2021,  author: 'Stephen King',     },
    { is_reading: false,   title: "Billy Summers",                                   year_published: 2021,  author: 'Stephen King',     },
    { is_reading: false,   title: "Gwendy's Final Task",                             year_published: 2022,  author: 'Stephen King',     },
    { is_reading: false,   title: "Fairy Tale",                                      year_published: 2022,  author: 'Stephen King',     },
    { is_reading: false,   title: "Holly",                                           year_published: 2023,  author: 'Stephen King',     },
    { is_reading: false,   title: "Never Finish",                                    year_published: 2025,  author: 'Stephen King',     },
]